import type { Metadata } from "next";
import { Cherry_Bomb_One, Modak, Shadows_Into_Light, Autour_One } from "next/font/google";
import "./globals.css";

export const cherryBomb = Cherry_Bomb_One({
  variable: "--font-cherry-bomb-one",
  subsets: ["latin"],
  weight: "400"
});

export const modak = Modak({
  variable: "--font-modak",
  subsets: ["latin"],
  weight: "400"
});

export const shawdowsIntoLight = Shadows_Into_Light({
  variable: "--font-shadows-into-light",
  subsets: ["latin"],
  weight: "400"
});

export const autourOne = Autour_One({
  variable: "--font-autour-one",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
